---
name: Book tests

on:
  push:
    branches:
      main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: hjwp/github-actions@v4
        with:
          test_chapter: test_chapter_01

#    - name: Test chapter 2 unittest
#      if: always()
#      run: |
#        make test_chapter_02_unittest
#
#    - name: Test chapter 3 first view
#      if: always()
#      run: |
#        make test_chapter_03_unit_test_first_view
#
#    - name: Test chapter 4 philosophy
#      if: always()
#      run: |
#        make test_chapter_04_philosophy_and_refactoring
#
#    - name: Test chapter 5 post and db
#      if: always()
#      run: |
#        make test_chapter_05_post_and_database
#
#    - name: Test chapter 6 explicit waits
#      if: always()
#      run: |
#        make test_chapter_06_explicit_waits_1
#
#    - name: Test chapter 7 working incrementally
#      if: always()
#      run: |
#        make test_chapter_07_working_incrementally
#
#    - name: Test chapter 8 prettification
#      if: always()
#      run: |
#        make test_chapter_08_prettification
#
#    - name: Test chapter 12 organising test files
#      if: always()
#      run: |
#        make test_chapter_12_organising_test_files
#
#    - name: Test chapter 13 basic validation
#      if: always()
#      run: |
#        make test_chapter_13_database_layer_validation
#
#    - name: Test chapter 14 simple form
#      if: always()
#      run: |
#        make test_chapter_14_simple_form
#
#    - name: Run unit tests
#      if: always()
#      run: |
#        ./tests/update_source_repo.py
#        ./run_test_tests.sh
#
#  # - name: Test all chapters in parallel, yolo
#  #   run: |
#  #     make build
#  #     pytest --tb=short --color=yes --numprocesses=4 tests/test_chapter_*
