---
name: Book tests

on:
  push:
    branches:
      main
  pull_request:

jobs:
  chapter-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        test_chapter: [
          test_chapter_01,
          test_chapter_02_unittest,
          test_chapter_03_unit_test_first_view,
          test_chapter_04_philosophy_and_refactoring,
          test_chapter_05_post_and_database,
          test_chapter_06_explicit_waits_1,
          test_chapter_07_working_incrementally,
          test_chapter_08_prettification,
          # test_chapter_09_docker,
          # test_chapter_10_production_readiness,
          # test_chapter_11_ansible,
          test_chapter_12_organising_test_files,
          test_chapter_13_database_layer_validation,
          test_chapter_14_simple_form,
        ]
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: hjwp/github-actions@v4
        with:
          test_chapter: ${{ matrix.test_chapter }}

#   unit-tests:
#     runs-on: ubuntu-latest
#     steps:
#       # todo: lots of duplication here with hjwp/github-actions@v4
#       - uses: actions/checkout@v3
#       - name: Set up Python 3.12
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.12
#       - name: Install Python requirements.txt
#         shell: bash
#         run: |
#           pip install -r requirements.txt
#
#       - name: Set locale
#         run: |
#           sudo locale-gen en_GB.UTF-8
#
#       - name: setup Git
#         shell: bash
#         run: |
#           git config --global user.email "elspeth@example.com"
#           git config --global user.name "Elspeth See-Eye"
#           git config --global init.defaultBranch main
#
#       - name: checkout unit test submodules
#         shell: bash
#         run: |
#           sed -i 's_git@github.com:_https://github.com/_' .gitmodules
#           git submodule update --init -- tests/testrepo
#
#       - name: Run unit tests
#         if: always()
#         run: |
#           SKIP_CHAPTER_SUBMODULES=1 ./tests/update_source_repo.py
#           ./run_test_tests.sh
