name: Book tests

on:
  push:
    branches:
      main
  pull_request:

jobs:
  tests:

    runs-on: ubuntu-latest

    env:
      MOZ_HEADLESS: 1
      LC_ALL: en_GB.UTF-8
      LANG: en_GB.UTF8
      LANGUAGE: "en_GB:en"

    steps:
    - uses: actions/checkout@v1

    - name: checkout submodules
      run: |
        sed -i 's_git@github.com:_https://github.com/_' .gitmodules
        git submodule update --init --recursive

    - name: setup Git
      run: |
        git config --global user.email "elspeth@example.com"
        git config --global user.name "Elspeth See-Eye"
        git config --global init.defaultBranch main

    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Install apt stuff and other dependencies
      run: |
        sudo apt update -y
        sudo apt install -y asciidoctor language-pack-en ruby-coderay firefox tree locales
        sudo locale-gen en_GB.UTF-8

    # - name: Install asciidoc and other ruby dependencies
    #   run: |
    #     sudo gem install coderay

    - name: Install Python requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check environment
      run: |
        locale -a
        locale
        env

    - name: Test chapter 1
      if: always()
      run: |
        make test_chapter_01

    - name: Test chapter 2
      if: always()
      run: |
        make test_chapter_02_unittest

    - name: Test chapter 3
      if: always()
      run: |
        make test_chapter_unit_test_first_view

    - name: Test chapter 4
      if: always()
      run: |
        make test_chapter_philosophy_and_refactoring

    - name: Test chapter 5
      if: always()
      run: |
        make test_chapter_post_and_database

    - name: Test chapter 6
      if: always()
      run: |
        make test_chapter_explicit_waits_1

    - name: Test chapter 7
      if: always()
      run: |
        make test_chapter_working_incrementally

    - name: Run unit tests
      if: always()
      run: |
        ./tests/update_source_repo.py
        ./run_test_tests.sh

  # - name: Test all chapters in parallel, yolo
  #   run: |
  #     make build
  #     pytest --tb=short --color=yes --numprocesses=4 tests/test_chapter_*
